include: package:flutter_lints/flutter.yaml # https://github.com/flutter/packages/tree/master/packages/flutter_lints

linter: # Lint rules: http://dart-lang.github.io/linter/lints/
  rules:
    type_annotate_public_apis: true # https://dart-lang.github.io/linter/lints/type_annotate_public_apis.html
    import_of_legacy_library_into_null_safe: true # https://dart-lang.github.io/linter/lints/import_of_legacy_library_into_null_safe.html
    avoid_types_on_closure_parameters: true # https://dart-lang.github.io/linter/lints/avoid_types_on_closure_parameters.html
    avoid_catching_errors: true # https://dart-lang.github.io/linter/lints/avoid_catching_errors.html
    prefer_mixin: true # https://dart-lang.github.io/linter/lints/prefer_mixin.html
    avoid_slow_async_io: true # https://dart-lang.github.io/linter/lints/avoid_slow_async_io.html
    cancel_subscriptions: true # https://dart-lang.github.io/linter/lints/cancel_subscriptions.html
    literal_only_boolean_expressions: true # http://dart-lang.github.io/linter/lints/literal_only_boolean_expressions.html
    no_adjacent_strings_in_list: true # http://dart-lang.github.io/linter/lints/no_adjacent_strings_in_list.html
    unnecessary_statements: true # http://dart-lang.github.io/linter/lints/unnecessary_statements.html
    unnecessary_string_escapes: false # https://dart-lang.github.io/linter/lints/unnecessary_string_escapes.html
    prefer_const_constructors_in_immutables: false # https://dart-lang.github.io/linter/lints/prefer_const_constructors_in_immutables.html
    prefer_const_literals_to_create_immutables: false # https://dart-lang.github.io/linter/lints/prefer_const_literals_to_create_immutables.html
    prefer_const_constructors: false # https://dart-lang.github.io/linter/lints/prefer_const_constructors.html
    prefer_const_declarations: false # https://dart-lang.github.io/linter/lints/prefer_const_declarations.html